image: fedora:28
variables:
    GIT_SUBMODULE_STRATEGY: recursive

stages:
    - build
    - bundle

build:linux:
    stage: build
    before_script:
    - dnf -y install gcc gcc-c++ make cmake libsodium-static.i686 libsodium-devel boost-static.i686 boost-devel glibc-static.i686 libstdc++-static.i686 glibc-devel.i686
    script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make
    artifacts:
        paths:
        - build/cryptosocket.ext.so

build:windows:
    stage: build
    tags: 
    - windows
    script:
    - 'call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\Common7\Tools\VsDevCmd.bat"'
    - cmake -DTARGET=windows -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build . --config Release
    artifacts:
        paths:
        - build/cryptosocket.ext.dll

bundle:all:
    stage: bundle
    script:
    - cd build
    - mkdir -p addons/sourcemod/extensions
    - cp cryptosocket.ext.so addons/sourcemod/extensions
    - cp cryptosocket.ext.dll addons/sourcemod/extensions
    - cp -r ../scripting addons/sourcemod
    - tar -cvf cryptosocket.tar.bz2 addons/
    dependencies:
    - build:linux
    - build:windows
    artifacts:
        paths:
        - build/cryptosocket.tar.bz2