FROM thedreae/devcontainer

USER root
RUN dnf -y install gcc gcc-c++ make cmake libsodium-static.i686 libsodium-devel boost-static.i686 boost-devel glibc-static.i686 libstdc++-static.i686 glibc-devel.i686

USER dev